// AntiShiftDeleteExt.idl: AntiShiftDeleteExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(AntiShiftDeleteExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(b8bc5b4b-d553-49eb-89b7-5aaa40b3f1fb),
	pointer_default(unique)
]
interface IFakeCopyHook : IUnknown
{
};
[
	object,
	uuid(7013f69b-a45d-4e58-a05b-e388d02b5e2b),
	pointer_default(unique)
]
interface IFakeObjectWithSite : IUnknown
{
};
[
	uuid(8dfe808e-bdb6-4387-8880-4102ab4fb322),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{e2bf26ce-52ed-4024-a7cd-d3501e5a4b7a}")
]
library AntiShiftDeleteExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(e2bf26ce-52ed-4024-a7cd-d3501e5a4b7a)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(49811806-ef1c-4967-b9fa-ee8410b357bc)
	]
	coclass FakeCopyHook
	{
		[default] interface IFakeCopyHook;
	};
	[
		uuid(33c79a3c-f0d2-4eb1-8f38-243071a1aae6)
	]
	coclass FakeObjectWithSite
	{
		[default] interface IFakeObjectWithSite;
	};
};

import "shobjidl.idl";
import "shobjidl.idl";
